name: Release UI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Use Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Use MY GH Action
        uses: AykutBurak/test-gh-action@v1
